apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: backend-migration
  name: backend-migration
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: backend-migration
        image: alorin/backend:b8e7df284fa343d577de17a58ceec2165a401d96
        command: ["npm", "run", "migrate"]
        env:
        - name: PORT
          value: "3000"
        - name: ADMIN_EMAIL
          value: admin@admin.fr
        - name: ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              key: admin-password
              name: backend
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              key: jwt-token
              name: backend
        - name: MONGO_URL
          value: mongodb://root:example@mongodb-svc:27017/
        - name: POSTGRE_HOST
          value: postgres-svc
        - name: POSTGRE_USER
          value: postgres
        - name: POSTGRE_PASSWORD
          value: example
        - name: POSTGRE_DATABASE
          value: app
        - name: OVH_ENDPOINT
          value: https://s3.gra.io.cloud.ovh.net
        - name: OVH_APP_KEY
          valueFrom:
            secretKeyRef:
              key: ovh-app-key
              name: backend
        - name: OVH_APP_SECRET
          valueFrom:
            secretKeyRef:
              key: ovh-app-token
              name: backend
        - name: GMAIL_USER
          valueFrom:
            secretKeyRef:
              key: gmail-user
              name: backend
        - name: GMAIL_PASSWORD
          valueFrom:
            secretKeyRef:
              key: gmail-password
              name: backend

        resources:
          requests:
            cpu: "128m"
        ports:
        - containerPort: 3000
          protocol: TCP
        readinessProbe:
          httpGet:
            port: 3000
            path: /api/health
      terminationGracePeriodSeconds: 60
