version: '3.6'

services:
  mongo:
    image: mongo
    container_name: database
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - db-data:/data/db

volumes:
  db-data:
