apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mongodb
  name: mongodb
spec:
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: root
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: example
        resources:
          requests:
            cpu: "128m"
        ports:
        - containerPort: 27017
          protocol: TCP
        volumeMounts:
            - mountPath: "/etc/mongo"
              name: mongodb-data
              readOnly: false
      volumes:
        - name: mongodb-data
          persistentVolumeClaim:
            claimName: mongodb-data
      terminationGracePeriodSeconds: 60
  minReadySeconds: 60