kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongodb-data
  labels:
    app: mongodb
spec:
  storageClassName: csi-cinder-classic
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi