name: Format

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  dev-check:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, ]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: cd app-back && npm ci

      - name: Launch linting
        run: cd app-back && npm run lint
